In [1]:
import hmm

test_data = [[0, 1, 2, 3, 4, 5] for _ in range(100)]
test_states = [[5, 4, 3, 2, 1, 0] for _ in range(100)]

HMM = hmm.supervised_HMM(test_data, test_states)
# HMM.O

In [2]:
# HMM.T

In [3]:
HMM.generate_emission(15)

[0. 0. 1. 0. 0. 0.]
[0. 1. 0. 0. 0. 0.]
[1. 0. 0. 0. 0. 0.]
[0.16666667 0.16666667 0.16666667 0.16666667 0.16666667 0.16666667]
[0.16666667 0.16666667 0.16666667 0.16666667 0.16666667 0.16666667]
[1. 0. 0. 0. 0. 0.]
[0.16666667 0.16666667 0.16666667 0.16666667 0.16666667 0.16666667]
[0. 0. 1. 0. 0. 0.]
[0. 1. 0. 0. 0. 0.]
[1. 0. 0. 0. 0. 0.]
[0.16666667 0.16666667 0.16666667 0.16666667 0.16666667 0.16666667]
[1. 0. 0. 0. 0. 0.]
[0.16666667 0.16666667 0.16666667 0.16666667 0.16666667 0.16666667]
[0.16666667 0.16666667 0.16666667 0.16666667 0.16666667 0.16666667]
[0. 0. 1. 0. 0. 0.]


([2, 3, 4, 5, 5, 4, 5, 2, 3, 4, 5, 4, 5, 5, 2],
 [3, 2, 1, 0, 0, 1, 0, 3, 2, 1, 0, 1, 0, 0, 3])

In [4]:
HMM.viterbi([0, 1, 2, 3, 4])

[5, 4, 3, 2, 1]

In [5]:
HMM_u = hmm.unsupervised_HMM(test_data, 6, 30)

epoch 1/30
epoch 2/30
epoch 3/30
epoch 4/30


d:\coding\pythonhmm\hmm.py:323: RuntimeWarning: invalid value encountered in divide
  self.A_start /= np.sum(self.A_start)
d:\coding\pythonhmm\hmm.py:177: RuntimeWarning: invalid value encountered in divide
  beta_b /= np.sum(beta_b)


epoch 5/30
epoch 6/30
epoch 7/30
epoch 8/30
epoch 9/30
epoch 10/30
epoch 11/30
epoch 12/30
epoch 13/30
epoch 14/30
epoch 15/30
epoch 16/30
epoch 17/30
epoch 18/30
epoch 19/30
epoch 20/30
epoch 21/30
epoch 22/30
epoch 23/30
epoch 24/30
epoch 25/30
epoch 26/30
epoch 27/30
epoch 28/30
epoch 29/30
epoch 30/30


In [6]:
HMM_u.generate_emission(15)

ValueError: probabilities contain NaN